# Array Manipulation

In [2]:
import numpy as np

x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [2]:
y = x.reshape(3, 2) #Reshape the vector x as a 3x2 matrix
print(y)

[[0 1]
 [2 3]
 [4 5]]


In [3]:
x = np.array([[0, 1, 2], [3, 4, 5]], dtype = np.uint8)
print(x)

[[0 1 2]
 [3 4 5]]


In [8]:
y = np.reshape(x, 6) #same as y = x.reshape(1, 6)
print(y)

[0 1 2 3 4 5]


In [9]:
y = np.ravel(x)
print(y)

[0 1 2 3 4 5]


In [10]:
y = x.flatten()
print(y)

[0 1 2 3 4 5]


In [11]:
y = x.flatten('C') #Flatten ordered by rows
print(y)

[0 1 2 3 4 5]


In [12]:
y = x.flatten('F') #Flatten ordered by columns
print(y)

[0 3 1 4 2 5]


In [13]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(x.dtype) #You can display the default data type of the arrays

print(x)
print(y)

int64
[1 2 3]
[4 5 6]


In [4]:
x = np.array([1, 2, 3], dtype = np.uint8)
y = np.array([4, 5, 6], dtype = np.uint8)

print(x.dtype) 

print(x)
print(y)

uint8
[1 2 3]
[4 5 6]


In [15]:
z = np.stack((x, y))
print(z)

[[1 2 3]
 [4 5 6]]


In [16]:
z = np.stack((x, y), axis = 1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
z = np.dstack((x, y)) #same as before
print(z)

[[[1 4]
  [2 5]
  [3 6]]]


In [7]:
print(z.shape)

(1, 3, 2)


In [8]:
z = np.hstack((x, y)) #stack everything horizontally
print(z)

[1 2 3 4 5 6]


In [9]:
z = np.vstack((x, y)) #same as the first stack
print(z)

[[1 2 3]
 [4 5 6]]


In [10]:
print(z.shape)

(2, 3)


In [11]:
x = np.arange(9)
print(x)

[0 1 2 3 4 5 6 7 8]


In [12]:
a, b, c = np.split(x, 3) #splits x in 3 separated arrays
print(a, b, c)

[0 1 2] [3 4 5] [6 7 8]


In [13]:
x = np.random.rand(4, 4, 4) #generates a random array of 4 dimensions with the size of 4x4
print(x)

[[[3.76448137e-01 5.18247418e-02 7.67420751e-01 4.98412965e-01]
  [3.77063295e-01 9.84001485e-01 9.14129343e-01 4.20485593e-01]
  [1.11249517e-01 7.67307440e-01 8.34774326e-01 1.06002211e-01]
  [9.46099271e-01 1.12843246e-01 8.14190196e-01 5.25669788e-01]]

 [[3.67546815e-01 2.40398847e-01 6.60656415e-01 2.05799703e-01]
  [5.52029750e-01 3.74221698e-01 7.26479175e-02 4.42501849e-01]
  [4.55824656e-01 7.51144705e-01 6.36989972e-01 2.76522493e-01]
  [8.83890242e-01 3.96584152e-01 1.80337786e-01 5.95566394e-01]]

 [[6.00464268e-01 6.91863632e-01 8.56064852e-01 8.37316723e-01]
  [4.83990692e-01 9.87734941e-01 7.24164016e-01 3.88647557e-01]
  [4.21485706e-01 8.57711337e-01 9.92951846e-01 3.19231345e-01]
  [5.36826386e-01 1.54870578e-01 6.84160785e-02 6.09449018e-01]]

 [[3.98689316e-01 3.75566263e-05 1.75551707e-02 4.99659997e-01]
  [8.86056077e-01 8.95090239e-01 9.56505839e-01 2.25912906e-01]
  [2.57243007e-01 5.87425790e-01 1.83006440e-01 7.98807340e-01]
  [2.83050032e-02 3.36541357e-01 7

In [15]:
y, z = np.split(x, 2)
print(y, z)

[[[0.37644814 0.05182474 0.76742075 0.49841296]
  [0.37706329 0.98400148 0.91412934 0.42048559]
  [0.11124952 0.76730744 0.83477433 0.10600221]
  [0.94609927 0.11284325 0.8141902  0.52566979]]

 [[0.36754682 0.24039885 0.66065642 0.2057997 ]
  [0.55202975 0.3742217  0.07264792 0.44250185]
  [0.45582466 0.75114471 0.63698997 0.27652249]
  [0.88389024 0.39658415 0.18033779 0.59556639]]] [[[6.00464268e-01 6.91863632e-01 8.56064852e-01 8.37316723e-01]
  [4.83990692e-01 9.87734941e-01 7.24164016e-01 3.88647557e-01]
  [4.21485706e-01 8.57711337e-01 9.92951846e-01 3.19231345e-01]
  [5.36826386e-01 1.54870578e-01 6.84160785e-02 6.09449018e-01]]

 [[3.98689316e-01 3.75566263e-05 1.75551707e-02 4.99659997e-01]
  [8.86056077e-01 8.95090239e-01 9.56505839e-01 2.25912906e-01]
  [2.57243007e-01 5.87425790e-01 1.83006440e-01 7.98807340e-01]
  [2.83050032e-02 3.36541357e-01 7.32723353e-01 4.25341388e-01]]]


In [16]:
x = np.arange(16).reshape(4, 4)
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [17]:
y = np.flip(x) #Inverts all the contents of the array
print(y)

[[15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [18]:
y = np.flip(x, axis = -1) #Inverts all the contents of the array like a mirror
print(y)

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [19]:
y = np.fliplr(x) #same as before
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]
 [15 14 13 12]]


In [20]:
y = np.flipud(x) #Up and down
print(x)
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [21]:
y = np.roll(x, 8) #A rotation of 8 elements
print(y)

[[ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]]


In [22]:
y = np.rot90(x)
print(y)

[[ 3  7 11 15]
 [ 2  6 10 14]
 [ 1  5  9 13]
 [ 0  4  8 12]]
