# Numpy Exercise 2
ndarray properties

In [3]:
import numpy as np

In [4]:
z = np.array([[[1, 2, 3], [4, 5, 6]], [[0, -1, -2], [-3, -4, -5]]], np.int16) 
print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [21]:
print(z.shape) #Size of the array
print(z.ndim) #Dimension of the array
print(z.dtype) #Data type of the array
print(z.size) #Number of elements in the array
print(z.nbytes) #Number of bytes of the array

(2, 2, 3)
3
int16
12
24


In [12]:
print(z.T) #The tranverse matrix of the array (Transpuesta)

[[[ 1  0]
  [ 4 -3]]

 [[ 2 -1]
  [ 5 -4]]

 [[ 3 -2]
  [ 6 -5]]]


# Numpy Constants

In [20]:
print(np.inf)
print(np.nan)

print(np.e)
print(np.euler_gamma)
print(np.pi)

inf
nan
2.718281828459045
0.5772156649015329
3.141592653589793
