# Numpy Exercise 1
Indexing and slicing ndarrays

In [3]:
import numpy as np

x = np.array([1, 2, 3], np.int16)

In [21]:
print(x)

print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
print(x[0]); print(x[1]); print(x[2])

1
2
3


In [6]:
print(x[-1]) #prints the last value of the array

3


In [8]:
y = np.array([[1, 2, 3], [4, 5, 6]], np.int16)
print(y)

[[1 2 3]
 [4 5 6]]


In [12]:
print(y[0,0]); print(y[0,1]); print(y[1,1])  

1
2
5


In [13]:
print(y[:,0]) #Prints column 0

[1 4]


In [14]:
print(y[:,2]) #Prints column 2

[3 6]


In [15]:
print(y[0, :]) #Prints row 0

[1 2 3]


In [16]:
z = np.array([[[1, 2, 3], [4, 5, 6]], [[0, -1, -2], [-3, -4, -5]]], np.int16) 
print(z)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 0 -1 -2]
  [-3 -4 -5]]]


In [17]:
print(z[0, 1, 2]) #Prints from matrix 0 value 1,2

6


In [18]:
print(z[1, 1, 1]) #Prints from matrix 1 value 1,1

-4


In [19]:
print(z[:, :, 1]) #Prints column 1 from both matrix

[[ 2  5]
 [-1 -4]]


In [20]:
print(z[:, 0, 1]) #Prints from both matrix values indexed by 0,1

[ 2 -1]
