# Arrays and Matplotlib
One and Zeros

In [1]:
import numpy as np

x = np.empty([3, 3], np.uint8) #And array with random values
print(x)

[[244  55   3]
 [  0   0   0]
 [  0   0   0]]


In [2]:
y = np.eye(3, dtype = np.uint8) #Matriz identidad
print(y)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [3]:
y = np.eye(5, dtype = np.uint8, k = 1) #Matriz identidad desplazada a la derecha
print(y)

[[0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]
 [0 0 0 0 0]]


In [4]:
y = np.eye(5, dtype = np.uint8, k = -1) #Matriz identidad desplazada a la izquierda
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]]


In [5]:
x = np.identity(5, dtype = np.uint8)
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [6]:
x = np.ones((2, 5, 5), dtype = np.int16) #Two matrix with 5x5 dimension filled with ones
print(x)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [7]:
x = np.zeros((2, 5, 5), dtype = np.int16) #Two matrix with 5x5 dimension filled with zeros
print(x)

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [8]:
x = np.full((3, 3, 3), dtype = np.int16, fill_value = 7) #Three matrix with 3x3 dimension filled with sevens
print(x)

[[[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]

 [[7 7 7]
  [7 7 7]
  [7 7 7]]]


# Matrix creation routines

In [10]:
x = np.tri(3, 3, k = 0, dtype = np.uint16)
print(x)

[[1 0 0]
 [1 1 0]
 [1 1 1]]


In [11]:
x = np.tri(5, 5, k = 1, dtype = np.uint16)
print(x)

[[1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [12]:
x = np.tri(5, 5, k = -1, dtype = np.uint16)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [13]:
x = np.ones((5,5), dtype = np.uint8)
y = np.tril(x, k = -1) #Triangular matrix with the lower values filled
print(y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [1 1 0 0 0]
 [1 1 1 0 0]
 [1 1 1 1 0]]


In [17]:
x = np.ones((5,5), dtype = np.uint8)
y = np.triu(x, k = 0) #Triangular matrix with the upper values filled
print(y)

[[1 1 1 1 1]
 [0 1 1 1 1]
 [0 0 1 1 1]
 [0 0 0 1 1]
 [0 0 0 0 1]]
