# Numpy and Random

In [1]:
import numpy as np

In [2]:
x = np.random.randint(low = 0, high = 9, size =10)
print(x)

[7 4 7 4 4 7 1 7 0 4]


In [3]:
x = np.random.rand(3,3)
print(x)

[[0.82977352 0.64690214 0.35413149]
 [0.59819133 0.18915378 0.8856828 ]
 [0.59903473 0.66631558 0.96865566]]


In [4]:
x = np.random.rand(2, 4, 4)
print(x)

[[[0.22953426 0.43326511 0.20288513 0.66200775]
  [0.46614905 0.93822071 0.70873265 0.87243382]
  [0.92774918 0.65609964 0.83555624 0.27051438]
  [0.89988733 0.12721213 0.86173299 0.63270131]]

 [[0.29634367 0.61445821 0.62713666 0.36960654]
  [0.90238524 0.26451902 0.17646441 0.58520408]
  [0.95645444 0.36400382 0.35092808 0.15992642]
  [0.23937765 0.29190648 0.17767131 0.67446156]]]
