# Bitwise Operations

In [1]:
import numpy as np

x = np.array([0, 1, 0, 1], np.uint8)
y = np.array([0, 0, 1, 1], np.uint8)

print(np.bitwise_and(x, y)) #AND operations between two vectors (same size)

[0 0 0 1]


In [2]:
print(np.bitwise_or(x, y)) #OR operations between two vectors
print(np.bitwise_xor(x, y)) #AND operations between two vectors
print(np.bitwise_not(y)) #NOT operation for "y" vector the results shows the complement of and 8 bit 0 and 00000001

[0 1 1 1]
[0 1 1 0]
[255 255 254 254]
